### PR TITLE
Started working on the sprint challange-Web-Tools-And-Framework

### PR DESCRIPTION
**Pull request by adfaris**
Started working on the challenge for today.

### CODE REVIEW

**Comment by adfaris** [comment]
Imported the Less files into index.less and compiled it.

**Comment by adfaris** [comment]
The general layout is complete, I have added a Carousel too.

**Comment by adfaris** [comment]
Added margins and override the a tag color so that it matches the spacewalker-desktop.png file

**Comment by adfaris** [comment]
I have commented out the first navbar and i have introduced JS component Navbar.

**Comment by adfaris** [comment]
Used mixins .box-shadow(String) for space-walker image with this specification: 
.box-shadow(0 5px 5px gray);

**Comment by adfaris** [comment]
realized my .box-shadow mixins is not working right and added border radius for the same pic

**Comment by AndjDavis** [comment]
Reviewed 1:1

**Comment by jaspindersingh83** [comment]
Hey AD, great code organization and putting a great effort for carousel. Here are few feedback points
1) Answers could have been more clearer if we write the whole command. for eg: '-g' can avoided and whole command can be written.
2) Use Block element modifiers in HTML (even if we are suing solutions like bootstrap and LESS)
3) One great practice would be to rethink the code in jsx after we have written in basic css and html.
codepen.io is a great tool to fiddle around with html and css.

**Pull request closed without merging**
